version: '3.1'
services:
  ghost:
    image: ghost:latest
    restart: always
    ports:
      - 8080:2368
    environment:
      database__client: mysql
      database__connection__host: db
      database__connection__user: root
      database__connection__password: example
      database__connection__database: ghost
    volumes:
      - ghostdata:/var/lib/ghost/content
    networks:
      - mynetwork

  db:
    image: mysql:5.7
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - dbdata:/var/lib/mysql
    networks:
      - mynetwork

  backup1:
    image: ubuntu:latest
    volumes:
      - backup1data:/backup
    networks:
      - mynetwork
    command: /bin/sh -c "while true; do tar -czf /backup/backup1.tar.gz /var/lib/mysql; sleep 3600; done"

  backup2:
    image: ubuntu:latest
    volumes:
      - backup2data:/backup
    networks:
      - mynetwork
    command: /bin/sh -c "while true; do tar -czf /backup/backup2.tar.gz /var/lib/mysql; sleep 3600; done"

volumes:
  ghostdata:
  dbdata:
  backup1data:
  backup2data:

networks:
  mynetwork: